### ISSUE TITLE
你好，如何在页脚添加备案号

### ISSUE THREAD

**Issue by teemo0803** [YukiCoco/OLAINDEX-Magic#19]
### 1. 该问题的重现步骤是什么？找不到页面文件
![image](https://user-images.githubusercontent.com/49296645/74906735-d5a57880-53ec-11ea-81fa-12a6d0c50551.png)

### 3. 问题出现的环境 正常

- 操作系统版本：正常
- Apache/NGINX 版本：正常
- PHP 版本：正常
- OLAINDEX 版本：正常
- 浏览器版本：正常

[//]: # (如有图片请附上截图)

**Comment by YukiCoco** [comment]
后台设置
