### ISSUE TITLE
记录几个原版发现的问题

### ISSUE THREAD

**Issue by fxzxmicah** [YukiCoco/OLAINDEX-Magic#4]
暂时没有时间尝试，所以先将在原版（ver 4.0_pre_2）中发现的问题记录在这里，有时间后再做尝试，希望作者可以对照修复一下（如果已经修复可以将我忽略）。
1. 上传组件问题。反馈这个问题的人不多，但是也有一些。我无论在何种环境下尝试，使用新版图床上传组件filepond上传总是出错，而旧版组件没有问题（后台也使用的是旧版组件）。
2. 二级目录问题。原版程序对二级目录安装使用的兼容性不是很好。我发现的一个问题就是删除时由于程序内使用了绝对路径会导致重定向的路径出错，直接访问了根目录（本来应该是example.com/dir/file/delete/结果重定向到example.com/file/delete/），而且在我自己改完源码后虽然功能可以使用，访问后会执行删除命令，但是却会在当前页返回一个500错误（但是此时文件确实已经被删除了）。
3. 这个是我的一点意见吧，由于我对微软那些API不是很懂，所以不知道获取到的文件直链是固定的还是动态的。由于现在原版程序获取直链的速度还是很慢（尤其把程序用作图床），所以如果是固定的可以把它的直链缓存下来，存在Redis之类的地方。如果是动态的希望作者还能优化一下解析速度，非常感谢。

**Comment by fxzxmicah** [comment]
补充：
1. 对于第一点可以参照[这里](https://github.com/WangNingkai/OLAINDEX/commit/47215cb3423f39d43e345ac2a579b216f1f995ad)将代码改成修改前的就可以。如果你可以解决filepond的上传出错问题，或者你有自己的其它解决方案也可以。（顺带一提，filepond的出错在后台并没有错误日志，所以我也不知道究竟是什么问题。）
2. 对于第二点，我的修改方案是修改[这里](https://github.com/WangNingkai/OLAINDEX/blob/5def811ff73cf1fe842e3e2cbf1c8a27619e68b4/resources/views/default/one.blade.php#L41)，在/file/delete/前加入自己的二级目录。但是如果不在二级目录中使用（在example.com中使用而不是example.com/dir），并且不做修改，删除文件并不会返回500错误，所以应该是还有我没有顾及到的地方。
3. 我的laravel的二级目录使用方案是网上介绍的将server.php修改为index.php使用，所以希望作者可以顾及到这点。

**Comment by fxzxmicah** [comment]
再补充：其实我是一个PHP小白，希望不要鄙视我😂😂

**Comment by YukiCoco** [comment]
1. filepond 出错是因为原作者设置的超时时间过短，在魔改版本中重新设置了超时时间。见：[这里](https://github.com/YukiCoco/OLAINDEX-Magic/blob/master/resources/views/default/image.blade.php#L53)
2. 魔改版本中采用了 Ajax 的方式删除，此问题解决。见：[这里](https://github.com/YukiCoco/OLAINDEX-Magic/blob/master/resources/views/default/one.blade.php#L79)
3. 直链缓存是会失效的，并不能永久地保存，这取决于你在后台设置的缓存保存时间。

**Comment by fxzxmicah** [comment]
好的，等我有时间我会尝试使用一下的。目前……你也知道嘛，考试周。
