### ISSUE TITLE
反馈两个问题。

### ISSUE THREAD

**Issue by fxzxmicah** [YukiCoco/OLAINDEX-Magic#5]
1. 开启路径兼容模式后设置图床为首页失效（原版就存在这个问题），而且访问example.com/1时提示404（应该是把1当做onedrive中存在的目录或者文件处理了）。
2. 二级目录问题（不是很明白为什么很多程序都不支持二级目录呢？二级目录对收录和权重友好，而且对于没有域名或者只有单域名的人来说也是一种解决方案啊）。laravel官方给出的二级目录方案就是把server.php改成index.php。错误图在下面。还是资源引用的问题。

**Comment by fxzxmic** [comment]
![image](https://user-images.githubusercontent.com/54622331/71522964-deecfa00-2901-11ea-9182-d079e18f63e2.png)

**Comment by YukiCoco** [comment]
1. 新版本已修复这个问题。
2. 建议手动修改找不到的 404 文件为静态资源，似乎没有比这个更好的办法。

**Comment by fxzxmicah** [comment]
其实还有个问题，图床上传图片会报错405，没有错误日志，F12里面显示405错误。 @YukiCoco

**Comment by YukiCoco** [comment]
> 其实还有个问题，图床上传图片会报错405，没有错误日志，F12里面显示405错误。 @YukiCoco

没有日志，仅根据这个说法难以重现错误。

**Comment by fxzxmicah** [comment]
其实我也不知道怎么回事，用原来的上传组件从来没出过问题，自从换成filepond我就从来没成功上传过。 @YukiCoco
