### ISSUE TITLE
无法绑定

### ISSUE THREAD

**Issue by jackjieYYY** [YukiCoco/OLAINDEX-Magic#7]
### 1. 该问题的重现步骤是什么？
初始化设置 填入id 密匙 和 地址
### 3. 问题出现的环境

- 操作系统版本：debian
- Apache/NGINX 版本：1.16
- PHP 版本：7.3
- OLAINDEX 版本：lasted
- 浏览器版本：chrome

[//]: # (如有图片请附上截图)
![image](https://user-images.githubusercontent.com/53422254/71645360-3a1c5380-2d2b-11ea-9940-eaeb59121057.png)

**Comment by YukiCoco** [comment]
参考：https://github.com/WangNingkai/OLAINDEX/issues/198

**Comment by jackjieYYY** [comment]
> 参考：[WangNingkai/OLAINDEX#198](https://github.com/WangNingkai/OLAINDEX/issues/198)

Thanks
